# 应用名称
spring:
  application:
    name: demo-03
server:
  port: 8081
  servlet:
    session:
      timeout: 30
  tomcat:
    uri-encoding: UTF-8

# 自定义配置
age: 19
name: zhaodabao
personinfo:
  name: zhaoxiaobao
  age: 3


