# 应用名称
spring:
  application:
    name: config-server
  # 加载本地配置
  profiles:
    active: native
  # 加载resources目录下的config文件夹下所有配置文件，多个文件夹可用“,”隔开
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
#  # 这里可以获取远程Git配置文件
#  cloud:
#    config:
#      server:
#        git:
#          uri:
#          search-paths: dev
#          username: username
#          password: password

server:
  port: 28201

eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8087/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}